# Generated by Django 6.0.3 on 2026-03-25 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True, verbose_name='Тикер')),
                ('isin', models.CharField(blank=True, max_length=12, null=True, verbose_name='ISIN')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('asset_type', models.CharField(choices=[('Share', 'Акция'), ('Bond', 'Облигация'), ('ETF', 'Фонд'), ('Currency', 'Валюта')], max_length=20, verbose_name='Тип актива')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
            },
        ),
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название счета')),
                ('provider_type', models.CharField(choices=[('T-Invest_API', 'Т-Инвестиции (API)'), ('Manual', 'Ручной ввод')], max_length=20, verbose_name='Провайдер')),
                ('provider_account_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID счета у провайдера')),
                ('_encrypted_token', models.BinaryField(blank=True, null=True, verbose_name='Зашифрованный API-токен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Брокерский счет',
                'verbose_name_plural': 'Брокерские счета',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внешний ID (от брокера)')),
                ('operation_type', models.CharField(choices=[('Buy', 'Покупка'), ('Sell', 'Продажа'), ('Dividend', 'Дивиденды'), ('Tax', 'Налог'), ('Fee', 'Комиссия'), ('Deposit', 'Пополнение'), ('Withdrawal', 'Вывод')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Цена за единицу')),
                ('date', models.DateTimeField(verbose_name='Дата операции')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.brokeraccount')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.asset')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date'],
            },
        ),
    ]
