# Generated by Django 6.0.3 on 2026-03-26 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeraccount',
            name='provider_account_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID счета у провайдера'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.asset'),
        ),
    ]
