# Generated by Django 6.0.3 on 2026-03-26 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_brokeraccount_provider_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_transactions', to='portfolio.transaction', verbose_name='Родительская операция'),
        ),
    ]
