# Generated by Django 6.0.3 on 2026-04-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_transaction_parent_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа'), ('repayment', 'Погашение облигаций'), ('dividend', 'Дивиденды'), ('coupon', 'Купоны'), ('amortization', 'Амортизационные выплаты'), ('other_accrual', 'Прочие начисления'), ('commission', 'Комиссия'), ('tax', 'Налог'), ('tax_refund', 'Возврат налога'), ('expense', 'Расход'), ('deposit', 'Пополнение счета'), ('withdrawal', 'Вывод средств'), ('other_income', 'Прочие доходы'), ('other_expense', 'Прочие расходы'), ('conversion', 'Конвертация'), ('conversion_commission', 'Комиссия на конвертацию')], max_length=30, verbose_name='Тип операции'),
        ),
    ]
