# Generated by Django 6.0.3 on 2026-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_transaction_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accrued_int',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='НКД (накопленный купонный доход)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Удержанная комиссия'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='yield_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Финансовый результат (доходность)'),
        ),
    ]
