# Generated by Django 6.0.3 on 2026-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_transaction_accrued_int_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='figi',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='FIGI инструмента'),
        ),
        migrations.AddField(
            model_name='asset',
            name='instrument_uid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='UID инструмента у брокера'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=20, verbose_name='Тикер'),
        ),
    ]
